apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-echo
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: simple-echo
    app.kubernetes.io/name: simple-echo
    app.kubernetes.io/part-of: simple-echo
    app.openshift.io/runtime: java
  name: simple-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-echo
  template:
    metadata:
      labels:
        app: simple-echo
    spec:
      containers:
      - name: simple-echo
        imagePullPolicy: Always
        image: hashicorp/http-echo
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5678
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 5678
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5678
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5