apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-echo
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: simple-echo
    app.kubernetes.io/name: simple-echo
    app.kubernetes.io/part-of: simple-echo
    app.openshift.io/runtime: java
  name: simple-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-echo
  template:
    metadata:
      labels:
        app: simple-echo
    spec:
      containers:
      - name: simple-echo
        imagePullPolicy: Always
        image: hashicorp/http-echo
        args:
        - "-listen=:{{ .Values.port }}"
        - "-text='{{ .Values.text }}'"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: {{ .Values.port }}
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: {{ .Values.port }}
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5