{{- range $route := .Values.routes }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: echo
  name: echo
spec:
  port:
    targetPort: tcp-endpoint
  to:
    kind: Service
    name: {{ $route }}
    weight: 100
{{ end }}