apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: ntl-geekfest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://theriaultnicolas.github.io/geekfest/'
    targetRevision: 2.x
    chart: echo
    helm:
      parameters:
        - name: text
          value: Hello Geekfest 2021
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ntl-geekfest
  # syncPolicy: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
